// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'caption': string;
  'content': string;
  'cross': string;
  'image': string;
  'preview': string;
  'title': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
