// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inputs': string;
  'placeholder': string;
  'placeholderWrap': string;
  'queue': string;
  'queueSection': string;
  'settings': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
