// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'advancedControls': string;
  'advancedInputs': string;
  'advancedTogglerButton': string;
  'advancedTogglerWrap': string;
  'advancedWrap': string;
  'button': string;
  'checkboxGroup': string;
  'controlButtons': string;
  'controlGroups': string;
  'inputs': string;
  'placeholder': string;
  'placeholderWrap': string;
  'queue': string;
  'queueSection': string;
  'removeAllButton': string;
  'settings': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
