// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accent': string;
  'button': string;
  'loading-shimmer': string;
}
export const cssExports: CssExports;
export default cssExports;
